// Cel-shaded outlines.
//
// The technique is an inverted hull: for each mesh, a copy is made whose
// vertices are pushed out along their normals, drawn with front faces culled so
// only the far side survives. What you see is a shell peeking out from behind
// the silhouette — which means the outline is generated by the geometry itself
// and follows the true silhouette from every angle, rather than being a fixed
// border stuck around a shape.
//
// The expansion is baked into a cloned geometry rather than done in a shader.
// That costs a little memory and buys two things: it works on SKINNED meshes
// for free (the shell shares the skeleton, so it deforms with the pose), and it
// depends on no shader chunk names, which move between three.js releases.

import * as THREE from 'three';

const KEY = '__outline';

/** Push every vertex out along its normal, into a new geometry. */
function swellGeometry(geo, amount) {
  const out = geo.clone();
  const pos = out.attributes.position;
  let nrm = out.attributes.normal;
  if (!nrm) { out.computeVertexNormals(); nrm = out.attributes.normal; }
  for (let i = 0; i < pos.count; i++) {
    pos.setXYZ(
      i,
      pos.getX(i) + nrm.getX(i) * amount,
      pos.getY(i) + nrm.getY(i) * amount,
      pos.getZ(i) + nrm.getZ(i) * amount,
    );
  }
  pos.needsUpdate = true;
  // the shell is flat-shaded ink; normals and UVs on it are dead weight
  out.deleteAttribute('uv');
  out.deleteAttribute('uv1');
  out.computeBoundingBox();          // the clone inherits a stale cached box
  out.computeBoundingSphere();
  return out;
}

/**
 * Give an object a drawn outline.
 *
 * `thickness` is in world units at the object's own scale, so a small prop and
 * a character both read correctly without per-object tuning.
 */
export function addOutline(target, { color = '#12141a', thickness = 0.03, opacity = 1 } = {}) {
  if (!target) return null;
  removeOutline(target);

  const mat = new THREE.MeshBasicMaterial({
    color,
    side: THREE.BackSide,      // keep only the far side — the rim around the shape
    transparent: opacity < 1,
    opacity,
    // The shell must not write depth or it punches a hole in things drawn after
    // it; and it must lose depth ties to the real mesh rather than z-fighting.
    depthWrite: true,
    polygonOffset: true,
    polygonOffsetFactor: 1,
    polygonOffsetUnits: 1,
    fog: false,
  });

  const shells = [];
  // Thickness is a WORLD measure, but the swelling happens in each mesh's own
  // geometry space — and those two can be wildly different. A skinned avatar's
  // geometry is authored in tiny bind-pose units that the bones scale up, so a
  // fixed local expansion came out enormous and swallowed the character whole.
  //
  // Measuring the object as it is actually drawn, and converting through that
  // ratio, gets the same ink width on a 1-unit cube and on a rigged character
  // without either needing special handling.
  target.updateMatrixWorld(true);
  const worldBox = new THREE.Box3().setFromObject(target);
  const worldSize = new THREE.Vector3();
  worldBox.getSize(worldSize);
  const worldSpan = Math.max(worldSize.x, worldSize.y, worldSize.z) || 1;

  target.traverse((o) => {
    if (!o.isMesh || o.userData.__isOutlineShell) return;
    if (!o.geometry.boundingBox) o.geometry.computeBoundingBox();
    const gs = new THREE.Vector3();
    o.geometry.boundingBox.getSize(gs);
    const geoSpan = Math.max(gs.x, gs.y, gs.z) || 1;
    // local units per world unit, for this mesh as it is really drawn
    const amount = thickness * (geoSpan / worldSpan);
    const geo = swellGeometry(o.geometry, amount);
    let shell;
    if (o.isSkinnedMesh) {
      shell = new THREE.SkinnedMesh(geo, mat);
      shell.bind(o.skeleton, o.bindMatrix);       // deform with the same pose
    } else {
      shell = new THREE.Mesh(geo, mat);
    }
    shell.userData.__isOutlineShell = true;
    shell.renderOrder = (o.renderOrder || 0) - 1;  // behind its own mesh
    shell.frustumCulled = o.frustumCulled;
    shell.matrixAutoUpdate = false;
    shell.matrix.identity();                       // rides the source mesh exactly
    o.add(shell);
    shells.push(shell);
  });

  target.userData[KEY] = { shells, mat };
  return target.userData[KEY];
}

/** Take the outline off again, releasing what it allocated. */
export function removeOutline(target) {
  const rec = target?.userData?.[KEY];
  if (!rec) return;
  for (const s of rec.shells) {
    s.parent?.remove(s);
    s.geometry.dispose();
  }
  rec.mat.dispose();
  delete target.userData[KEY];
}

export const hasOutline = (target) => !!target?.userData?.[KEY];

/** Restyle an existing outline without rebuilding its geometry. */
export function setOutlineStyle(target, { color, opacity } = {}) {
  const rec = target?.userData?.[KEY];
  if (!rec) return false;
  if (color) rec.mat.color.set(color);
  if (opacity != null) { rec.mat.opacity = opacity; rec.mat.transparent = opacity < 1; }
  return true;
}

// ---------------------------------------------------------------- cel shading
// A toon ramp: lighting is quantised into a few flat bands instead of a smooth
// falloff, which is what makes an outlined object read as drawn rather than
// rendered. Three's MeshToonMaterial does the banding; it just needs the ramp.
let RAMP = null;
function toonRamp(steps = 3) {
  if (RAMP) return RAMP;
  const data = new Uint8Array(steps * 4);
  for (let i = 0; i < steps; i++) {
    const v = Math.round(70 + (185 * i) / Math.max(1, steps - 1));
    data[i * 4] = data[i * 4 + 1] = data[i * 4 + 2] = v;
    data[i * 4 + 3] = 255;
  }
  RAMP = new THREE.DataTexture(data, steps, 1, THREE.RGBAFormat);
  RAMP.needsUpdate = true;
  RAMP.minFilter = RAMP.magFilter = THREE.NearestFilter;
  return RAMP;
}

/**
 * Swap an object's materials for banded toon equivalents, keeping their colour
 * and map. Reversible: the originals are stashed on each mesh.
 */
export function setCelShaded(target, on = true, steps = 3) {
  if (!target) return;
  target.traverse((o) => {
    if (!o.isMesh || o.userData.__isOutlineShell) return;
    if (on) {
      if (o.userData.__preToon) return;
      const src = Array.isArray(o.material) ? o.material : [o.material];
      o.userData.__preToon = o.material;
      const toon = src.map((m) => new THREE.MeshToonMaterial({
        color: m?.color ? m.color.clone() : new THREE.Color('#ffffff'),
        map: m?.map || null,
        gradientMap: toonRamp(steps),
        vertexColors: !!m?.vertexColors,
        transparent: !!m?.transparent,
        opacity: m?.opacity ?? 1,
        side: m?.side ?? THREE.FrontSide,
      }));
      o.material = Array.isArray(o.material) ? toon : toon[0];
    } else if (o.userData.__preToon) {
      const cur = Array.isArray(o.material) ? o.material : [o.material];
      for (const m of cur) m?.dispose?.();
      o.material = o.userData.__preToon;
      delete o.userData.__preToon;
    }
  });
}
